version: '3.9'
services:
  redis:
    container_name: "redis"
    image: redis:alpine
    # Specify the redis.conf file to use and add a password.
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  api1:
      container_name: "api1"
      build: api1
      environment:
        REDIS_HOST: cache
        REDIS_PORT: 6379
        REDIS_PASSWORD: password
      ports: 
        - 5000:5000
      depends_on:
        - redis
  api2:
      container_name: "api2"
      build: api2
      environment:
        REDIS_HOST: cache
        REDIS_PORT: 6379
        REDIS_PASSWORD: password
      ports: 
        - 5001:5000
      depends_on:
        - redis
  ui:
      container_name: "ui"
      build: ui
      ports: 
        - 3000:3000
  nginx-proxy:
    depends_on: 
    - ui
    - api1
    - api2
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  mongoauth: